### ISSUE TITLE
Desafios Médios JavaScript  - Polígonos Regulares Simples

### ISSUE THREAD

**Issue by lourranio** [lucasrmagalhaes/desafios-DIO#21]
Na geometria Euclidiana, um polígono regular é um polígono em que todos os ângulos são iguais e todos os lados tem o mesmo comprimento. Um polígono simples é aquele cujos segmentos de reta não se interceptam. Abaixo pode-se ver vários mosaicos feitos por polígonos regulares.

https://ibb.co/5G1wDdm
<a href="https://imgbb.com/"><img src="https://i.ibb.co/HBK3v06/C-1.jpg" alt="C-1" border="0"></a>

Você deve escrever um programa que, dados o número e o comprimento dos lados de um polígono regular, mostre seu perímetro.

Entrada
A entrada tem dois inteiros positivos: N e L, que são, respectivamente, o número de lados e o comprimento de cada lado de um polígono regular (3 ≤ N ≤ 1000000 and 1 ≤ L ≤ 4000).

Saída
A saída é o perímetro P do polígono regular em uma única linha.

https://ibb.co/whmTTSm
<a href="https://imgbb.com/"><img src="https://i.ibb.co/Df2NN92/s.png" alt="s" border="0"></a>

 

**CODIGO DE INICIO**

`let lines = gets().split("\n");
let line = lines.shift().split(' ');

//continue o seu código aqui`

**Comment by lucasrmagalhaes** [comment]
Esse desafio faz parte da DIO?

**Comment by lourranio** [comment]
> Esse desafio faz parte da DIO?

Sim .. Curso "impulso-react-web-developer"

**Comment by lourranio** [comment]
resposta 


`let line = gets().split(' ');

let a = parseInt(line[0]);
let b = parseInt(line[1]);
let q = parseInt(a*b);
 console.log(q);`

**Comment by lourranio** [comment]
https://ibb.co/dDzWHsR

<a href="https://ibb.co/dDzWHsR"><img src="https://i.ibb.co/ZxkLbR0/img3.png" alt="img3" border="0"></a>

**Comment by lucasrmagalhaes** [comment]
@lourranio postei no repo!

**Comment by pedrajade** [comment]
Alguem poderia me ajudar com o código completo, acabei apagando o enunciado, e agora não consigo voltar ! Por favor ? @lucasrmagalhaes
