### ISSUE TITLE
[Solução][JavaScript] Uniformes de final de ano

### ISSUE THREAD

**Issue by rbalves** [lucasrmagalhaes/desafios-DIO#31]
# Uniformes de final de ano
## Desafio
O professor Girafales organizou a confecção de um uniforme para as turmas da escola para comemorar o final do ano. Após algumas conversas, ficou decidido com os alunos que eles poderiam escolher a cor do uniforme entre branco ou vermelho. Assim sendo, Girafales precisa de sua ajuda para organizar as listas de quem quer o uniforme em cada uma das turmas, relacionando estas camisetas pela cor, tamanho (P, M ou G) e por último pelo nome.

### Entrada
Cada caso de teste inicia com um valor N, (1 ≤ N ≤ 60) inteiro e positivo, que indica a quantidade de uniformes a serem feitas para aquela turma. As próximas N*2 linhas contém informações de cada um dos uniformes (serão duas linhas de informação para cada uniforme). A primeira linha irá conter o nome do estudante e a segunda linha irá conter a cor do uniforme ("branco" ou "vermelho") seguido por um espaço e pelo tamanho do uniforme "P" "M" ou "G". A entrada termina quando o valor de N for igual a zero (0) e esta valor não deverá ser processado.

### Saída
Para cada caso de entrada deverão ser impressas as informações ordenadas pela cor em ordem ascendente, seguido pelos tamanhos em ordem descendente e por último por ordem ascendente de nome, conforme o exemplo abaixo.

**Comment by rbalves** [comment]
## Solução proposta
```
let nUniformes = parseInt(gets());

let uniformes = [];

while (nUniformes > 0) {
  let nome = gets();
  let corTamanho = gets();
  
  const [cor, tamanho] = corTamanho.split(" ");
  
  uniformes.push({ nome, cor, tamanho });
  
  nUniformes--;
}

uniformes.sort((a,b) => {
  if (a.cor > b.cor) return 1;
  if (a.cor < b.cor) return -1;
  if (a.tamanho > b.tamanho) return -1;
  if (a.tamanho < b.tamanho) return 1;
  if (a.nome > b.nome) return 1;
  if (a.nome < b.nome) return -1;
  return 0;
});

for (let uniforme of uniformes) {
  const { cor, nome, tamanho } = uniforme;
  console.log(`${cor} ${tamanho} ${nome}`)
}
```

**Comment by lucasrmagalhaes** [comment]
Adicionado.
