### ISSUE TITLE
[Solução][JavaScript] Gincana no Acampamento

### ISSUE THREAD

**Issue by rbalves** [lucasrmagalhaes/desafios-DIO#33]
# Gincana no Acampamento
## Desafio
Nas férias de Dezembro, várias escolas se organizam e levam seus alunos para um acampamento de férias por uma semana. Nestes acampamentos os alunos são divididos em cabanas coletivos por gênero e idade, sempre com um adulto que, além de dormir com o grupo no cabana, também são responsáveis por criar e executar várias atividades, como por exemplo jogos, excursões, Gincanas Noturnas, etc.

No primeiro dia foi realizada uma gincana em que a atividade constituia em agrupar os alunos em um círculo (organizado no sentido anti-horário) do qual seriam retiradas uma a uma até que sobrasse apenas um aluno, que seria o vencedor.

No momento em que entra no círculo, cada aluno recebe uma pequena ficha que contém um valor de 1 a 500. Depois que o círculo é formado, conta-se, iniciando no aluno que está ao lado da primeira que entrou no círculo, o número correspondente à ficha que o primeiro detém. O aluno onde o número contado cair, deve ser retirado do grupo, e a contagem inicia novamente segundo a ficha do aluno que acabou de ser eliminado. Para ficar mais interessante, quando o valor que consta na ficha é par, a contagem é feita no sentido horário e quando o valor que consta na ficha é ímpar, a contagem é feita no sentido anti-horário.

Desenvolva um programa para que no próximo evento o responsável pela brincadeira saiba previamente qual criança irá ser a vencedora de cada grupo, com base nas informações fornecidas.

### Entrada
A entrada contém vários casos de teste. A primeira linha de cada caso de teste contém um inteiro N (1 ≤ N ≤ 100), indicando a quantidade de alunos que farão parte de cada círculo. Em seguida, as N linhas de cada caso de teste conterão duas informações, o Nome e o Valor (1 ≤ Valor ≤ 500) que consta na ficha de cada aluno, separados por um espaço, na ordem de entrada na formação do círculo inicial.

OBS: O Nome de cada aluno não deverá ultrapassar 30 caracteres e contém apenas letras maiúsculas e minúsculas, sem acentos, e o caractere “_”. O final da entrada é indicado pelo número zero.

### Saída
Para cada caso de teste, deve-se apresentar a mensagem Vencedor(a): xxxxxx, com um espaço após o sinal ":" indicando qual é o aluno do grupo que venceu a brincadeira.

**Comment by rbalves** [comment]
## Solução proposta
```
while (true) {
  let N = gets();
  
  if (N === "0") break;

  let circulo = [];
  
  for (let i = 0; i < parseInt(N); i++) {
    const [nome, ficha] = gets().split(" ");
    circulo.push([nome, ficha]);
  }
  
  function buscarPosicaoAtual(ficha, posicaoAtual, totalAlunos) {
  	const fichaEhPar = ficha % 2 === 0;
    const contaNoSentidoAntiHorario = () => posicaoAtual --;
    const contaNoSentidoHorario = () => posicaoAtual ++;
  
    if (fichaEhPar) {
      contaNoSentidoAntiHorario();
    } else {
      contaNoSentidoHorario();
    }
    
    const chegouNoUltimo = posicaoAtual > totalAlunos - 1;
    const chegouNoPrimeiro = posicaoAtual < 0;
    
    const voltarProInicio = () => posicaoAtual = 0;
    const voltarProFim = () => posicaoAtual = totalAlunos - 1;
  
    if (chegouNoUltimo) {
      voltarProInicio();
    }
  
    if (chegouNoPrimeiro) {
      voltarProFim();
    }
    
    return posicaoAtual;
  }
  
  function realizarContagem (ficha, posicaoAtual, totalAlunos) {
    for (let i = 0; i < ficha - 1; i++) {
    	posicaoAtual = buscarPosicaoAtual(ficha, posicaoAtual, totalAlunos)
    }
    
    return posicaoAtual;
  }
  
  let posicaoAtual = 0;
  
  let ficha = circulo[posicaoAtual][1];
  
  let totalAlunos = circulo.length;
  
  posicaoAtual = buscarPosicaoAtual(ficha, posicaoAtual, totalAlunos);
  
  let [alunoRemovido] = circulo[posicaoAtual];
  
  while (totalAlunos > 1) {
    posicaoAtual = realizarContagem(ficha, posicaoAtual, totalAlunos);
  
    alunoRemovido = circulo[posicaoAtual][0];
    
    ficha = circulo[posicaoAtual][1];
    
    let posicaoIniciaContagem = buscarPosicaoAtual(ficha, posicaoAtual, totalAlunos)
    
    let [alunoIniciaContagem] = circulo[posicaoIniciaContagem];
  
   	circulo = circulo.filter(([aluno]) => aluno !== alunoRemovido);
    
    totalAlunos = circulo.length;
  
   	posicaoAtual = circulo.map(([aluno]) => aluno).indexOf(alunoIniciaContagem)
  }
  
  const [[vencedor]] = circulo;
  
  console.log(`Vencedor(a): ${vencedor}`);
}
```

**Comment by lucasrmagalhaes** [comment]
Adicionado.
