### ISSUE TITLE
[Solução][JavaScript] Encontre a maior substring

### ISSUE THREAD

**Issue by rbalves** [lucasrmagalhaes/desafios-DIO#34]
# Encontre a maior substring
## Desafio
Encontre a maior substring comum entre as duas strings informadas. A substring pode ser qualquer parte da string, inclusive ela toda. Se não houver subseqüência comum, a saída deve ser “0”. A comparação é case sensitive ('x' != 'X').

### Entrada
A entrada contém vários casos de teste. Cada caso de teste é composto por duas linhas, cada uma contendo uma string. Ambas strings de entrada contém entre 1 e 50 caracteres ('A'-'Z','a'-'z' ou espaço ' '), inclusive, ou no mínimo uma letra ('A'-'Z','a'-'z').

### Saída
O tamanho da maior subsequência comum entre as duas Strings.

**Comment by rbalves** [comment]
## Solução proposta
```
let firstString = "";
let secondString = "";

while(firstString = gets()) {
  secondString = gets()
  
  let sizeLongestSubstring = 0;
  
  for(let i = 0; i <= firstString.length; i++) {
    for(let j = 0; j <= firstString.length; j++) {
      const substring = firstString.substr(i, j);
      
      if(secondString.includes(substring) && substring.length > sizeLongestSubstring) {
        sizeLongestSubstring = substring.length;
      }
    }
  }
  
  console.log(sizeLongestSubstring);
}

```

**Comment by lucasrmagalhaes** [comment]
Qual bootcamp/desafio é esse?
