### ISSUE TITLE
Desafio

### ISSUE THREAD

**Issue by CristianoDaSilvaFerreira** [lucasrmagalhaes/desafios-DIO#4]
Desculpa, não achei outra forma de entra em contato com você, mas estou preso nesse desafio, e olhando aqui no Git vi seu código, mas ao usar ele, o mesmo não passou.
Estou tentando resolver esse desafio e não consigo

**Comment by lucasrmagalhaes** [comment]
Qual desafio?

Em qua, 3 de mar de 2021 18:30, CRISTIANO DA SILVA FERREIRA <
notifications@github.com> escreveu:

**Comment by CristianoDaSilvaFerreira** [comment]
Desafio
O calendário escolar está passando bem rápido, devido a isso, as professoras de uma escola estão com dificuldade para calcular as notas dos alunos. Visando em resolver a situação, a diretora da escola contratou você para desenvolver um programa que leia as notas da primeira e da segunda avaliação de um aluno. Calcule e imprima a média semestral.

O programa só aceitará notas válidas (uma nota válida deve pertencer ao intervalo [0,10]). Cada nota deve ser validada separadamente.

No final deve ser impressa a mensagem “novo calculo (1-sim 2-nao)”, solicitando as professoras que informe um código (1 ou 2) indicando se ele deseja ou não executar o algoritmo novamente, (aceitar apenas os código 1 ou 2). Se for informado o código 1 deve ser repetida a execução de todo o programa para permitir um novo cálculo, caso contrário o programa deve ser encerrado.

Entrada
O arquivo de entrada contém vários valores reais, positivos ou negativos. Quando forem lidas duas notas válidas, deve ser lido um valor inteiro X . O programa deve parar quando o valor lido para este X for igual a 2.

Saída
Se uma nota inválida for lida, deve ser impressa a mensagem “nota invalida”. Quando duas notas válidas forem lidas, deve ser impressa a mensagem “media = ” seguido do valor do cálculo.

Antes da leitura de X deve ser impressa a mensagem "novo calculo (1-sim 2-nao)" e esta mensagem deve ser apresentada novamente se o valor da entrada padrão para X for menor do que 1 ou maior do que 2, conforme o exemplo abaixo.

A média deve ser impressa com dois dígitos após o ponto decimal.

**Comment by lucasrmagalhaes** [comment]
using System;
using System.Collections.Generic;
using System.Globalization;

namespace programa_para_validacao_de_notas
{
    class Program
    {
        static void Main(string[] args)
        {
            double opcaoUsuario = 1.00;

            do
            {
                List<double> notasValidas = new List<double> { };
                double somaDasNotas = 0, media;

                while (notasValidas.Count != 2)
                {
                    double nota = double.Parse(Console.ReadLine(), CultureInfo.InvariantCulture);

                    if (nota < 0.0 || nota > 10.0)
                    {
                        Console.WriteLine("nota invalida");
                    }
                    else
                    {
                        notasValidas.Add(nota);
                    }
                }

                foreach (double nota in notasValidas)
                {
                    somaDasNotas += nota;
                }

                media = somaDasNotas / notasValidas.Count;
                Console.WriteLine("media = {0}", media.ToString("F2", CultureInfo.InvariantCulture));

                do
                {
                    Console.WriteLine("novo calculo (1-sim 2-nao)");
                    opcaoUsuario = double.Parse(Console.ReadLine());
                } while ((opcaoUsuario != 1 && opcaoUsuario != 2) && opcaoUsuario != 2);

            } while (opcaoUsuario != 2.00);
        }
    }

    class ValidaNota
    {
        private bool nota;
    }
}

**Comment by thiagoviks** [comment]
Estou tentando resolver o mesmo desafio em javascript e não consigo, ainda estou aprendendo javascript e não consigo reescrever seu código C# em javascript, poderia me ajudar. Obrigado.

**Comment by Jonisson-Gomes** [comment]
Thiagoviks, estamos no mesmo barco amigo...

**Comment by lucasrmagalhaes** [comment]
Qual o bootcamp vocês estão fazendo?

**Comment by Jonisson-Gomes** [comment]
Localiza React

**Comment by lucasrmagalhaes** [comment]
```js
let resposta = '1';

while (resposta == '1') {
  let num1 = +gets();
  let num2 = +gets();

  while (num1 < 0 || num1 > 10) {
    console.log("nota invalida");
    num1 = +gets();
  }

  while (num2 < 0 || num2 > 10) {
    console.log("nota invalida");
    num2 = +gets();
  }

  console.log(`media = ${((num1 + num2) / 2).toFixed(2)}`)
  resposta = "";

  while (resposta != 1 && resposta !=2) {
    console.log("novo calculo (1-sim 2-nao)");
    resposta = +gets();
  }
}
```

**Comment by Jonisson-Gomes** [comment]
Eu consegui entender um pouco da lógica @lucasrmagalhaes  porém no JS tem algumas coisas a mais(O enunciado é o mesmo), porém o código disponibilizado para alteração está exatamente assim:

`let getout = false;

let numA = null;
let numB = null;

while (          ) {
  const num = Number(lines.shift());

  if (           ) {
    console.log("nota invalida");
    continue;
  }

  if (           ) {
  

  }

  numB = num;

  const average =   
  
  let validResponse = false;
  
  numA = null;
  numB = null;
  
  console.log("media = " + average.toFixed(2));

  let response = null;
  
  do {
    console.log(                       );

    response = lines.shift();

    switch (response) {
      case "1":
       

      case "2":
        
    }
  } while (               );
}`

**Comment by lucasrmagalhaes** [comment]
Eu rodei lá e funcionou. Pode apagar e adicionar o código.

**Comment by Jonisson-Gomes** [comment]
@lucasrmagalhaes value man, ajudou caramba, eu quero muito a minha cabeça com esses enunciados da DIO. Obrigado man!

**Comment by matheusmaia103** [comment]
Esse foi! Valeu, estava preso nesse mesmo desafio

**Comment by matheusmaia103** [comment]
alguém conseguiu aquele do fibonacci também? n sei pq que o teste não tá passando

**Comment by brennerdiasmartins** [comment]
Ola tudo bem? Nao consigo fazer o desafio "Média Final do Aluno" poderia me ajudar?
