### ISSUE TITLE
[Bug] Descrição de desafio incorreta ou duplicada

### ISSUE THREAD

**Issue by rbalves** [lucasrmagalhaes/desafios-DIO#40]
No README, nas soluções implementadas em JavaScript, na tabela "Ordenação e Filtros em Javascript", o título do primeiro desafio está incorreto ou duplicado. O link está direcionando para a solução do desafio "Ordenando Números Pares e Ímpares".

![image](https://user-images.githubusercontent.com/26890154/152623538-e0ea8bc4-9150-4a5d-9e19-8a6e4382335b.png)

**Comment by lucasrmagalhaes** [comment]
Resolvido!
